spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: root
        loginPassword: sasa
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      primary: appconfig
      druid:
        # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        # validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小 MySQL下建议关闭
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          username: root
          password: sasa
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.107:3306/lzproduct_config?userUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        # 多数据源配置
        appconfig:
          username: root
          password: sasa
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.107:3306/lzproduct_config?userUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        applog:
          username: root
          password: sasa
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.107:3306/lzapplog?userUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        app:
          username: root
          password: sasa
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.107:3306/lzframe?userUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
  #字段值为null时不做返回
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    # json数据中null字段不显示解决方法
    # default-property-inclusion: non_null

mybatis-plus:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/**/*Mapper.xml
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
logging:
  config: classpath:log4j2.xml
security:
  oauth2:
    client:
      client-id: user-client
      client-secret: 123456
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: dev
    access-token-uri: http://localhost:8080/oauth/token
